app/routes/main.py
from flask import Blueprint, render_template

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    return render_template('index.html', title='Home')

app/sign_to_text/__init__.py
from flask import Blueprint

sign_to_text_bp = Blueprint('sign_to_text', __name__, url_prefix='/sign_to_text',
                   template_folder='templates',
                   static_folder='static')

from app.sign_to_text import routes  # Import routes after creating blueprint   

app/text_to_sign/__init__.py
from flask import Blueprint

text_to_sign_bp = Blueprint('text_to_sign', __name__, url_prefix='/text_to_sign',
                   template_folder='templates',
                   static_folder='static')

from app.text_to_sign import routes  # Import routes after creating blueprint

app/templates/includes/navbar.html
{% block navbar %}
<nav>
    <div class="nav-wrapper">
        <a href="{{ url_for('main.index') }}" class="brand">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo">
            <span>HandSpeak Innovators</span>
        </a>
        <ul class="nav-links">
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            <li><a href="{{ url_for('text_to_sign.index') }}">Text to Sign</a></li>
            <li><a href="{{ url_for('sign_to_text.index') }}">Sign to Text</a></li>
            <li><a target="_blank" href="http://localhost:5000/">Learning</a></li>
            <li><a target="_blank" href="http://localhost:3000/">HandSpeak Community</a></li>
        </ul>
    </div>
</nav>
{% endblock %}